### ISSUE TITLE
No User Found

### ISSUE THREAD

**Issue by skabirgithub** [yukitaka13-1110/flutter_webrtc_agora_example#1]
it shows no user found

**Comment by yukitaka13-1110** [comment]
Hi @skabirgithub .

I think you should create agora project and retrieve agora app id from there.
Then you write it to the following file.

https://github.com/yukitaka13-1110/flutter_webrtc_agora_example/blob/8c4e5dbdea249c278bb05289009968f0ff3c6b2e/lib/utils/constants.dart#L1-L4

Please check [this article](https://qiita.com/yukitaka13-1110/items/e7350a5bc50f2056253f).

Best regards!

**Comment by skabirgithub** [comment]
I provided sir. I am getting the error from my web version.

![image](https://user-images.githubusercontent.com/17235603/112751417-cc271080-8fef-11eb-855d-027e5ba52012.png)


WebRtcController: init()
Error: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)
    at Object.throw_ [as throw] (http://localhost:54785/dart_sdk.js:4348:11)
    at MethodChannel._invokeMethod (http://localhost:54785/packages/flutter/src/services/system_channels.dart.lib.js:943:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:54785/dart_sdk.js:37956:33
    at _RootZone.runUnary (http://localhost:54785/dart_sdk.js:37810:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:54785/dart_sdk.js:32771:29)
    at handleValueCallback (http://localhost:54785/dart_sdk.js:33319:49)
    at Function._propagateToListeners (http://localhost:54785/dart_sdk.js:33357:17)
    at _Future.new.[_completeWithValue] (http://localhost:54785/dart_sdk.js:33199:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:54785/dart_sdk.js:33222:35)
    at Object._microtaskLoop (http://localhost:54785/dart_sdk.js:38071:13)
    at _startMicrotaskLoop (http://localhost:54785/dart_sdk.js:38077:13)
    at http://localhost:54785/dart_sdk.js:33574:9

**Comment by yukitaka13-1110** [comment]
@skabirgithub I see.
Please check [this issue](https://github.com/flutter/flutter/issues/65515).
I haven't never build and run on web platform.

**Comment by skabirgithub** [comment]
Error: MissingPluginException(No implementation found for method create on channel agora_rtc_engine)
    at Object.throw_ [as throw] (http://localhost:55785/dart_sdk.js:4348:11)
    at MethodChannel._invokeMethod (http://localhost:55785/packages/flutter/src/services/system_channels.dart.lib.js:943:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:55785/dart_sdk.js:37956:33
    at _RootZone.runUnary (http://localhost:55785/dart_sdk.js:37810:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:55785/dart_sdk.js:32771:29)
    at handleValueCallback (http://localhost:55785/dart_sdk.js:33319:49)
    at Function._propagateToListeners (http://localhost:55785/dart_sdk.js:33357:17)
    at _Future.new.[_completeWithValue] (http://localhost:55785/dart_sdk.js:33199:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:55785/dart_sdk.js:33222:35)
    at Object._microtaskLoop (http://localhost:55785/dart_sdk.js:38071:13)
    at _startMicrotaskLoop (http://localhost:55785/dart_sdk.js:38077:13)
    at http://localhost:55785/dart_sdk.js:33574:9

**Comment by skabirgithub** [comment]
> @skabirgithub I see.
> Please check [this issue](https://github.com/flutter/flutter/issues/65515).
> I haven't never build and run on web platform.

sir can you please run on the web and help me to fix the issue?

**Comment by yukitaka13-1110** [comment]
@skabirgithub 
This plugin doesn't support web.
See [this](https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/214).

**Comment by skabirgithub** [comment]
> @skabirgithub 
> This plugin doesn't support web.
> See [this](https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/214).

Thank you so much sir. It’s really a great help from your references and response.

**Comment by yukitaka13-1110** [comment]
@skabirgithub You're welcome!
